included:
  - SmartUserDefaults/
excluded:
  - SmartUserDefaultsTests
  - Pods
  - vendor

disabled_rules:
  - line_length
  - trailing_whitespace
  - statement_position
  - force_cast

identifier_name:
    excluded:
      - ok
      - id
      - io